- trio_asyncio/adapter.py
- trio_asyncio/base.py
- trio_asyncio/loop.py
- trio_asyncio/util.py
This is obviously not yet done, as missing the cancellation handling.
Looking for some preliminary feedback.
It works for the following code:
```
import asyncio
import trio
import trio_asyncio
@trio_asyncio.trio2aio
async def asyncio_generator():
yield 1
await asyncio.sleep(1)
yield 2
async def async_main(*args):
async with trio_asyncio.open_loop() as loop:
async for m in asyncio_generator():
print(m)
trio.run(async_main)
```
> Support using asyncio async generators in trio.

- trio_asyncio/util.py
Using `==` can cause errors, for example using grpc items, which raise an exception if compared with arbitrary objects.
I notice you already merged the other pull request. Do you still want me to add a test case? Note also the lack of support proper cancellation currently.
> Async generators, continued

- setup.py
- trio_asyncio/adapter.py
- trio_asyncio/util.py
The new async generator support as-is means that trio-asyncio no longer imports on 3.5 at all, when before it did. While the docs say it's not officially supported, it worked just fine. In particular, I am using it with PyPy, which seems to support some kind of weird mixture between 3.5 and 3.6, but mostly 3.5 and no async generator syntax.
Every trio user already has the `async_generator` module installed anyway, since it is a hard dependency of trio itself. I think it is therefore an easy decision to use it to bring back PyPy support.
> Use async_generator module for 3.5 support.

- .appveyor.yml
- .travis.yml
- Makefile
- debian/changelog
- debian/control
- docs/source/conf.py
- docs/source/index.rst
- docs/source/usage.rst
- setup.cfg
- setup.py
- tests/aiotest/__init__.py
- tests/aiotest/test_callback.py
- tests/conftest.py
- tests/python/test_base_events.py
- tests/python/test_events.py
- tests/python/test_subprocess.py
- tests/python/test_tasks.py
- tests/python/test_windows_events.py
- tests/python/test_windows_utils.py
- tests/test_concurrent.py
- tests/test_sync.py
- trio_asyncio/_version.py
- trio_asyncio/base.py
- trio_asyncio/loop.py
> Release 0.8.0

- docs/source/rationale.rst
- docs/source/usage.rst
- newsfragments/49.bugfix.rst
- setup.py
- tests/interop/test_adapter.py
- tests/python/test_selector_events.py
- tests/python/test_subprocess.py
- trio_asyncio/async_.py
- trio_asyncio/base.py
- trio_asyncio/sync.py
Closes #46.
Releasing a new version of `trio-asyncio` with this change will unblock python-trio/pytest-trio#68 - cc @njsmith
> Upgrade from deprecated trio.Queue; fix tests; fix docs

- trio_asyncio/base.py
Otherwise these get reported as DeprecationWarning.
> Remove invalid escape sequences from docstrings

- MANIFEST.in
Fixes #75.
I'm not sure how the previous releases included the license files, since they don't appear to have ever been listed in the manifest, but I verified that a new `python setup.py sdist` does include them where it did not before this change.
> Update MANIFEST.in to include project metadata

- newsfragments/80.bugfix.rst
- trio_asyncio/_base.py
- trio_asyncio/_loop.py
I ran into some deadlocks and other issues ("loop must be stopped before it can be closed" during teardown) while writing tests for #76 that cancelled the open_loop() block. This fixes them, doesn't break anything else, and seems like a good idea in theory.
> Streamline handling of async loop exit

- .github/workflows/ci.yml
- ci.sh
- docs-requirements.txt
- docs/source/conf.py
- Run towncrier before building docs, so that errors in newsfragments get noticed by CI
- We have readthedocs CI integration set up now, so can drop the extra docs build in github actions
> Improve docs CI

- newsfragments/91.feature.rst
- tests/interop/test_calls.py
- tests/test_trio_asyncio.py
- trio_asyncio/_loop.py
This makes open_loop() work like asyncio.run(), giving "background" tasks a chance to unwind themselves, rather than simply abandoning them to the garbage collector.
Like asyncio.run(), we don't catch tasks that are spawned after delivering the cancellations -- those will get abandoned like before. This is maybe fixable in theory but it's probably more trouble than it's worth.
Fixes #91
> Cancel and join asyncio tasks when exiting an open_loop() block

- .github/workflows/ci.yml
- .readthedocs.yml
- docs/source/conf.py
- newsfragments/123.misc.rst
- setup.py
- trio_asyncio/_base.py
- trio_asyncio/_handles.py
- trio_asyncio/_util.py
Use `sniffio.thread_local` to indicate which async library is running, instead of the deprecated `sniffio.current_async_library_cvar`. This allows us to remove a number of workarounds for the contextvar being inherited where it shouldn't be, and is also necessary to interoperate with Trio 0.23 which uses the thread-local.
Fixes #123.
> Modernize sniffio integration

- newsfragments/115.bugfix.rst
- trio_asyncio/_loop.py
Resolves #115. This also modifies the "cancel and await all asyncio tasks" logic to run even if `open_loop()` is cancelled or sees an exception, because that's another potential source of deadlocks -- the Trio tasks in the `tasks_nursery` might need to block on asyncio work as they unwind.
> Fix potential deadlock if open_loop() is cancelled

- newsfragments/134.bugfix.rst
- tests/test_trio_asyncio.py
- trio_asyncio/_async.py
> Fix spew when event loop exception handler is invoked after loop closure

- docs-requirements.txt
- docs/source/principles.rst
- docs/source/usage.rst
- newsfragments/137.feature.rst
- setup.py
- tests/conftest.py
- trio_asyncio/_base.py
- trio_asyncio/_handles.py
- trio_asyncio/_loop.py
- trio_asyncio/_sync.py
> Use greenlets rather than threads for sync loop

- newsfragments/130.bugfix.rst
- trio_asyncio/_base.py
- trio_asyncio/_loop.py
Fixes #130. It is unreasonably difficult to fail gracefully upon exceeding this limit, and stock asyncio has no similar limit, so be unlimited by default and encourage users not to change that. We still leave the `queue_len` option in case someone has a good use for it.
> Use an infinite queue_len by default, and advise against reducing it

- docs-requirements.txt
- test-requirements.txt
0.25.0 causes some tests to fail - c.f. [release notes](https://github.com/python-trio/trio/releases)
> pin trio to <0.25.0 due to breaking changes

- newsfragments/143.bugfix.rst
- tests/test_trio_asyncio.py
- trio_asyncio/_base.py
Fixes  #143 
Ran `pytest` on both `master` and the branch with the fix - output is the same (there are existing failures):
- on `executor-double-acquire-fix`
```
=============================================== short test summary info ================================================
FAILED tests/interop/test_calls.py::TestCalls::test_trio_asyncio_cancel_direct - BaseExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
FAILED tests/test_misc.py::test_keyboard_interrupt_teardown - BaseExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
FAILED tests/test_misc.py::test_cancel_loop[True] - ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
FAILED tests/test_misc.py::test_run_trio_task_errors - BaseExceptionGroup: Exceptions from Trio nursery (1 sub-exception) …
```
> _base.py: fix double acquire by TrioExecuto, issue #143

- docs-requirements.txt
- newsfragments/146.misc.rst
- test-requirements.txt
- tests/interop/test_calls.py
- tests/test_misc.py
- tests/test_trio_asyncio.py
Fixes #146.
Technically it's only the tests that are impacted but for completeness I also bumped the `trio` version on `docs-requirements.txt`.
> [tests] support trio's new exception groups, bump min trio rev to 0.25.0

- newsfragments/149.bugfix.rst
- tests/test_trio_asyncio.py
- trio_asyncio/_sync.py
SystemExit passes through the asyncio loop, so the `stop()` callback scheduled by the main task's Future's completion doesn't run; which then means it's pending when we re-enter the asyncio loop to do cleanup tasks like `shutdown_asyncgens`. Fix by not enqueueing the `stop()` callback if we can tell that the exception is going to pass through the asyncio loop.
Relevant upstream issue: https://bugs.python.org/issue22429
> Fix spurious error when asyncio.run() task raises SystemExit

- newsfragments/92.feature.rst
- tests/conftest.py
- tests/test_trio_asyncio.py
- trio_asyncio/_base.py
- trio_asyncio/_loop.py
Install custom async generator hooks that finalize each asyncgen in the same context (trio vs asyncio mode, and the correct trio-asyncio loop if asyncio mode) as it was first iterated. Fixes #92.
> Finalize async generators in the correct context

- .readthedocs.yml
- docs/source/conf.py
- test-requirements.txt
- tests/test_misc.py
- tests/test_trio_asyncio.py
Trivial fix replacing `RaisesGroup(strict=False)` with `RaisesGroup(flatten_subgroups=True)` in tests (`strict` was deprecated in Trio 0.26 and removed in Trio 0.27 in October 2024).
Also fixes a couple of tiny docs-related issues that were breaking the docs build due to recent external changes, and thus failing CI:
1. RTD [now requires](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/) an explicit `configuration` setting specifying the config file.
2. Sphinx no longer requires an explicit call to `get_html_theme_path()`, and in fact warns `WARNING: Calling get_html_theme_path is deprecated. If you are calling it to define html_theme_path, you are safe to remove that code.` (and CI treats warns as errors).
Fixes #154
> fix RaisesGroup(strict=...) in tests, removed in trio 0.27

- .github/workflows/ci.yml
- .readthedocs.yml
- README.rst
- debian/control
- newsfragments/###.misc.rst
- setup.py
Update supported Python versions to follow Trio itself (and of course, 3.8 is EOL).
> Update supported Python versions - add 3.13, remove 3.8

- trio_asyncio/_loop.py
Changing `__name__` in the middle of the module causes subsequent definitions to have the mangled (and therefore incorrect) `__module__`, which causes a bad interaction with `cloudpickle` (which in turn needs to ensure pickled functions can be imported from their `__module__`). Moving the `__name__` change to the end of the module satisfies the [`DeprecationWarning` check](https://github.com/python/cpython/blob/42306978867e8999a32c99bb96923aa1bed4a42a/Lib/asyncio/events.py#L691) while sidestepping the above.
> Move __name__ mangling to end of module
